name: .NET Core

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events to branches matching refs/heads/releases/10
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:
      - v*           # Push events to v* tags

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup NBGV environment
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
      id: nbgv
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish Alopeyk.Net
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: src/Alopeyk.Net/Alopeyk.Net.csproj
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Alopeyk.Net.AspNet
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: src/Alopeyk.Net.AspNet/Alopeyk.Net.AspNet.csproj
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish Alopeyk.Net.JsonNet
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: src/Alopeyk.Net.JsonNet/Alopeyk.Net.JsonNet.csproj
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # PROJECT_FILE_PATH: src/Alopeyk.Net/Alopeyk.Net.csproj

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}

          # API key to authenticate with NuGet server
          # NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet package id, used for version detection & defaults to project name
          # PACKAGE_NAME: Core
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false
